In [459]:
import os
import pandas as pd
import numpy as np

In [460]:
def load_csv(path):
    full = os.path.join('diabetes', path)
    return pd.read_csv(full)

In [461]:
original = load_csv('diabetic_data_balanced.csv')
full = load_csv('diabetic_data_original.csv')

pd.set_option('display.max_columns', None)

original.head()

encounter_id  patient_nbr             race  gender      age weight  \
0       2278392      8222157        Caucasian  Female   [0-10)    NaN   
1        149190     55629189        Caucasian  Female  [10-20)    NaN   
2         64410     86047875  AfricanAmerican  Female  [20-30)    NaN   
3        500364     82442376        Caucasian    Male  [30-40)    NaN   
4         16680     42519267        Caucasian    Male  [40-50)    NaN   

   admission_type_id  discharge_disposition_id  admission_source_id  \
0                  6                        25                    1   
1                  1                         1                    7   
2                  1                         1                    7   
3                  1                         1                    7   
4                  1                         1                    7   

   time_in_hospital payer_code         medical_specialty  num_lab_procedures  \
0                 1        NaN  Pediatrics-Endocrinology                  41   
1                 3        NaN                       NaN                  59   
2                 2        NaN                       NaN                  11   
3                 2        NaN                       NaN                  44   
4                 1        NaN                       NaN                  51   

   num_procedures  num_medications  number_outpatient  number_emergency  \
0               0                1                  0                 0   
1               0               18                  0                 0   
2               5               13                  2                 0   
3               1               16                  0                 0   
4               0                8                  0                 0   

   number_inpatient  diag_1  diag_2 diag_3  number_diagnoses max_glu_serum  \
0                 0  250.83     NaN    NaN                 1          None   
1                 0     276  250.01    255                 9          None   
2                 1     648     250    V27                 6          None   
3                 0       8  250.43    403                 7          None   
4                 0     197     157    250                 5          None   

  A1Cresult metformin repaglinide nateglinide chlorpropamide glimepiride  \
0      None        No          No          No             No          No   
1      None        No          No          No             No          No   
2      None        No          No          No             No          No   
3      None        No          No          No             No          No   
4      None        No          No          No             No          No   

  acetohexamide glipizide glyburide tolbutamide pioglitazone rosiglitazone  \
0            No        No        No          No           No            No   
1            No        No        No          No           No            No   
2            No    Steady        No          No           No            No   
3            No        No        No          No           No            No   
4            No    Steady        No          No           No            No   

  acarbose miglitol troglitazone tolazamide examide citoglipton insulin  \
0       No       No           No         No      No          No      No   
1       No       No           No         No      No          No      Up   
2       No       No           No         No      No          No      No   
3       No       No           No         No      No          No      Up   
4       No       No           No         No      No          No  Steady   

  glyburide-metformin glipizide-metformin glimepiride-pioglitazone  \
0                  No                  No                       No   
1                  No                  No                       No   
2                  No                  No                       No   
3                  No                  No                       No   
4        

In [462]:
def proportions(df, field):
    print(df[field].value_counts() / df[field].value_counts().sum())

proportions(original, 'readmitted')
proportions(full, 'readmitted')
full.info()

>30    0.333333
NO     0.333333
<30    0.333333
Name: readmitted, dtype: float64
NO     0.539119
>30    0.349282
<30    0.111599
Name: readmitted, dtype: float64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 50 columns):
encounter_id                101766 non-null int64
patient_nbr                 101766 non-null int64
race                        101766 non-null object
gender                      101766 non-null object
age                         101766 non-null object
weight                      101766 non-null object
admission_type_id           101766 non-null int64
discharge_disposition_id    101766 non-null int64
admission_source_id         101766 non-null int64
time_in_hospital            101766 non-null int64
payer_code                  101766 non-null object
medical_specialty           101766 non-null object
num_lab_procedures          101766 non-null int64
num_procedures              101766 non-null int64
num_medications      

In [463]:
full.describe(include='all')

#['acetohexamide', 'examide', 'citoglipton', 'glipizide-metformin', 'glimepiride-pioglitazone', 'metformin-rosiglitazone', 'metformin-pioglitazone']

encounter_id   patient_nbr       race  gender      age  weight  \
count   1.017660e+05  1.017660e+05     101766  101766   101766  101766   
unique           NaN           NaN          6       3       10      10   
top              NaN           NaN  Caucasian  Female  [70-80)       ?   
freq             NaN           NaN      76099   54708    26068   98569   
mean    1.652016e+08  5.433040e+07        NaN     NaN      NaN     NaN   
std     1.026403e+08  3.869636e+07        NaN     NaN      NaN     NaN   
min     1.252200e+04  1.350000e+02        NaN     NaN      NaN     NaN   
25%     8.496119e+07  2.341322e+07        NaN     NaN      NaN     NaN   
50%     1.523890e+08  4.550514e+07        NaN     NaN      NaN     NaN   
75%     2.302709e+08  8.754595e+07        NaN     NaN      NaN     NaN   
max     4.438672e+08  1.895026e+08        NaN     NaN      NaN     NaN   

        admission_type_id  discharge_disposition_id  admission_source_id  \
count       101766.000000             101766.000000        101766.000000   
unique                NaN                       NaN                  NaN   
top                   NaN                       NaN                  NaN   
freq                  NaN                       NaN                  NaN   
mean             2.024006                  3.715642             5.754437   
std              1.445403                  5.280166             4.064081   
min              1.000000                  1.000000             1.000000   
25%              1.000000                  1.000000             1.000000   
50%              1.000000                  1.000000             7.000000   
75%              3.000000                  4.000000             7.000000   
max              8.000000                 28.000000            25.000000   

        time_in_hospital payer_code medical_specialty  num_lab_procedures  \
count      101766.000000     101766            101766       101766.000000   
unique               NaN         18                73                 NaN   
top                  NaN          ?                 ?                 NaN   
freq                 NaN      40256             49949                 NaN   
mean            4.395987        NaN               NaN           43.095641   
std             2.985108        NaN               NaN           19.674362   
min             1.000000        NaN               NaN            1.000000   
25%             2.000000        NaN               NaN           31.000000   
50%             4.000000        NaN               NaN           44.000000   
75%             6.000000        NaN               NaN           57.000000   
max            14.000000        NaN               NaN          132.000000   

        num_procedures  num_medications  number_outpatient  number_emergency  \
count    101766.000000    101766.000000      101766.000000     101766.000000   
unique             NaN              NaN                NaN               NaN   
top                NaN              NaN                NaN               NaN   
freq               NaN              NaN                NaN               NaN   
mean          1.339730        16.021844           0.369357          0.197836   
std           1.705807         8.127566           1.267265          0.930472   
min           0.000000         1.000000           0.000000          0.000000   
25%           0.000000        10.000000           0.000000          0.000000   
50%           1.000000        15.000000           0.000000          0.000000   
75%           2.000000        20.000000           0.000000          0.000000   
max           6.000000        81.000000          42.000000         76.000000   

        number_inpatient  diag_1  diag_2  diag_3  number_diagnoses  \
count      101766.000000  101766  101766  101766     101766.000000   
unique               NaN     717     749     790               NaN   
top                  NaN     428     276     250               NaN   
freq                 NaN    6862    6752

In [464]:
original.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 50 columns):
encounter_id                9999 non-null int64
patient_nbr                 9999 non-null int64
race                        9819 non-null object
gender                      9999 non-null object
age                         9999 non-null object
weight                      300 non-null object
admission_type_id           9999 non-null int64
discharge_disposition_id    9999 non-null int64
admission_source_id         9999 non-null int64
time_in_hospital            9999 non-null int64
payer_code                  235 non-null object
medical_specialty           6362 non-null object
num_lab_procedures          9999 non-null int64
num_procedures              9999 non-null int64
num_medications             9999 non-null int64
number_outpatient           9999 non-null int64
number_emergency            9999 non-null int64
number_inpatient            9999 non-null int64
diag_1                   

In [465]:
original.describe(include='all')

encounter_id   patient_nbr       race  gender      age    weight  \
count   9.999000e+03  9.999000e+03       9819    9999     9999       300   
unique           NaN           NaN          5       2       10         8   
top              NaN           NaN  Caucasian  Female  [70-80)  [75-100)   
freq             NaN           NaN       7181    5390     2693       128   
mean    3.216415e+07  2.616384e+07        NaN     NaN      NaN       NaN   
std     2.289500e+07  3.362519e+07        NaN     NaN      NaN       NaN   
min     1.252200e+04  1.350000e+02        NaN     NaN      NaN       NaN   
25%     1.622300e+07  2.425828e+06        NaN     NaN      NaN       NaN   
50%     2.698463e+07  8.794098e+06        NaN     NaN      NaN       NaN   
75%     3.790203e+07  3.230309e+07        NaN     NaN      NaN       NaN   
max     9.448424e+07  1.151968e+08        NaN     NaN      NaN       NaN   

        admission_type_id  discharge_disposition_id  admission_source_id  \
count         9999.000000               9999.000000          9999.000000   
unique                NaN                       NaN                  NaN   
top                   NaN                       NaN                  NaN   
freq                  NaN                       NaN                  NaN   
mean             2.455546                  4.733073             6.721972   
std              1.865877                  6.791574             4.995468   
min              1.000000                  1.000000             1.000000   
25%              1.000000                  1.000000             2.000000   
50%              2.000000                  1.000000             7.000000   
75%              3.000000                  6.000000             7.000000   
max              8.000000                 25.000000            20.000000   

        time_in_hospital payer_code medical_specialty  num_lab_procedures  \
count        9999.000000        235              6362         9999.000000   
unique               NaN         10                49                 NaN   
top                  NaN         MC  InternalMedicine                 NaN   
freq                 NaN        129              1974                 NaN   
mean            4.838984        NaN               NaN           46.870087   
std             3.167283        NaN               NaN           18.128148   
min             1.000000        NaN               NaN            1.000000   
25%             2.000000        NaN               NaN           35.000000   
50%             4.000000        NaN               NaN           47.000000   
75%             7.000000        NaN               NaN           59.000000   
max            14.000000        NaN               NaN          114.000000   

        num_procedures  num_medications  number_outpatient  number_emergency  \
count      9999.000000      9999.000000        9999.000000       9999.000000   
unique             NaN              NaN                NaN               NaN   
top                NaN              NaN                NaN               NaN   
freq               NaN              NaN                NaN               NaN   
mean          1.445645        15.303830           0.109311          0.064906   
std           1.724649         7.915417           0.589934          0.442184   
min           0.000000         1.000000           0.000000          0.000000   
25%           0.000000        10.000000           0.000000          0.000000   
50%           1.000000        14.000000           0.000000          0.000000   
75%           2.000000        19.000000           0.000000          0.000000   
max           6.000000        62.000000          12.000000         22.000000   

        number_inpatient diag_1 diag_2 diag_3  number_diagnoses max_glu_serum  \
count        9999.000000   9994   9954   9764       9999.000000          9999   
unique               NaN    441    421    462               NaN             4   
top                  NaN    414    428    250        

In [466]:
np.any(original['metformin-pioglitazone'] != 'No')

False

## Data manipulation

### Missing values & redundant columns
* Drop `weight`
* Drop `payer_code`
* Create an `unknown` group for `medical_speciality`
* Get rid of singular columns
* Get rid of columns that have nothing to do with prediction

In [467]:
df = original.copy()

def get_na_info(df):
    nas = df.isna().sum()
    nas = nas[nas > 0]
    return nas

print("NA info in the begginning:")
print(get_na_info(df))

df.drop('weight', axis=1, inplace=True)
df.drop('payer_code', axis=1, inplace=True)
df.drop('diag_1', axis=1, inplace=True)
df.drop('diag_2', axis=1, inplace=True)
df.drop('diag_3', axis=1, inplace=True)

df['medical_specialty'].fillna(value=unknown_token, inplace=True)
df['race'].fillna(value=unknown_token, inplace=True)

print("NA info after cleanup")
print(get_na_info(df))

NA info in the begginning:
race                  180
weight               9699
payer_code           9764
medical_specialty    3637
diag_1                  5
diag_2                 45
diag_3                235
dtype: int64
NA info after cleanup
Series([], dtype: int64)


In [468]:
df.describe(include='all')

encounter_id   patient_nbr       race  gender      age  \
count   9.999000e+03  9.999000e+03       9999    9999     9999   
unique           NaN           NaN          6       2       10   
top              NaN           NaN  Caucasian  Female  [70-80)   
freq             NaN           NaN       7181    5390     2693   
mean    3.216415e+07  2.616384e+07        NaN     NaN      NaN   
std     2.289500e+07  3.362519e+07        NaN     NaN      NaN   
min     1.252200e+04  1.350000e+02        NaN     NaN      NaN   
25%     1.622300e+07  2.425828e+06        NaN     NaN      NaN   
50%     2.698463e+07  8.794098e+06        NaN     NaN      NaN   
75%     3.790203e+07  3.230309e+07        NaN     NaN      NaN   
max     9.448424e+07  1.151968e+08        NaN     NaN      NaN   

        admission_type_id  discharge_disposition_id  admission_source_id  \
count         9999.000000               9999.000000          9999.000000   
unique                NaN                       NaN                  NaN   
top                   NaN                       NaN                  NaN   
freq                  NaN                       NaN                  NaN   
mean             2.455546                  4.733073             6.721972   
std              1.865877                  6.791574             4.995468   
min              1.000000                  1.000000             1.000000   
25%              1.000000                  1.000000             2.000000   
50%              2.000000                  1.000000             7.000000   
75%              3.000000                  6.000000             7.000000   
max              8.000000                 25.000000            20.000000   

        time_in_hospital medical_specialty  num_lab_procedures  \
count        9999.000000              9999         9999.000000   
unique               NaN                50                 NaN   
top                  NaN           unknown                 NaN   
freq                 NaN              3637                 NaN   
mean            4.838984               NaN           46.870087   
std             3.167283               NaN           18.128148   
min             1.000000               NaN            1.000000   
25%             2.000000               NaN           35.000000   
50%             4.000000               NaN           47.000000   
75%             7.000000               NaN           59.000000   
max            14.000000               NaN          114.000000   

        num_procedures  num_medications  number_outpatient  number_emergency  \
count      9999.000000      9999.000000        9999.000000       9999.000000   
unique             NaN              NaN                NaN               NaN   
top                NaN              NaN                NaN               NaN   
freq               NaN              NaN                NaN               NaN   
mean          1.445645        15.303830           0.109311          0.064906   
std           1.724649         7.915417           0.589934          0.442184   
min           0.000000         1.000000           0.000000          0.000000   
25%           0.000000        10.000000           0.000000          0.000000   
50%           1.000000        14.000000           0.000000          0.000000   
75%           2.000000        19.000000           0.000000          0.000000   
max           6.000000        62.000000          12.000000         22.000000   

        number_inpatient  number_diagnoses max_glu_serum A1Cresult metformin  \
count        9999.000000       9999.000000          9999      9999      9999   
unique               NaN               NaN             4         4         4   
top                  NaN               NaN          None      None        No   
freq                 NaN               NaN          9048      8177      8415   
mean            0.659166          6.892089           NaN       NaN       NaN   
std             1.351151          2.008747           NaN       NaN  

In [469]:
def get_unique_pairs(df):
    pairs = []
    
    for col in df.columns:
        pairs.append((col, df[col].unique().shape[0]))
    
    return pairs

def get_singular_cols(df):
    singular_cols = []
    unq_pairs = get_unique_pairs(df)
    
    for col, unq in unq_pairs:
        if unq == 1:
            singular_cols.append(col)
    return singular_cols

sing = get_singular_cols(df)
print("Singular columns before", sing)
df.drop(sing, axis=1, inplace=True)
print("Singular columns after", get_singular_cols(df))
df.describe(include='all')

Singular columns before ['acetohexamide', 'examide', 'citoglipton', 'glipizide-metformin', 'glimepiride-pioglitazone', 'metformin-rosiglitazone', 'metformin-pioglitazone']
Singular columns after []


encounter_id   patient_nbr       race  gender      age  \
count   9.999000e+03  9.999000e+03       9999    9999     9999   
unique           NaN           NaN          6       2       10   
top              NaN           NaN  Caucasian  Female  [70-80)   
freq             NaN           NaN       7181    5390     2693   
mean    3.216415e+07  2.616384e+07        NaN     NaN      NaN   
std     2.289500e+07  3.362519e+07        NaN     NaN      NaN   
min     1.252200e+04  1.350000e+02        NaN     NaN      NaN   
25%     1.622300e+07  2.425828e+06        NaN     NaN      NaN   
50%     2.698463e+07  8.794098e+06        NaN     NaN      NaN   
75%     3.790203e+07  3.230309e+07        NaN     NaN      NaN   
max     9.448424e+07  1.151968e+08        NaN     NaN      NaN   

        admission_type_id  discharge_disposition_id  admission_source_id  \
count         9999.000000               9999.000000          9999.000000   
unique                NaN                       NaN                  NaN   
top                   NaN                       NaN                  NaN   
freq                  NaN                       NaN                  NaN   
mean             2.455546                  4.733073             6.721972   
std              1.865877                  6.791574             4.995468   
min              1.000000                  1.000000             1.000000   
25%              1.000000                  1.000000             2.000000   
50%              2.000000                  1.000000             7.000000   
75%              3.000000                  6.000000             7.000000   
max              8.000000                 25.000000            20.000000   

        time_in_hospital medical_specialty  num_lab_procedures  \
count        9999.000000              9999         9999.000000   
unique               NaN                50                 NaN   
top                  NaN           unknown                 NaN   
freq                 NaN              3637                 NaN   
mean            4.838984               NaN           46.870087   
std             3.167283               NaN           18.128148   
min             1.000000               NaN            1.000000   
25%             2.000000               NaN           35.000000   
50%             4.000000               NaN           47.000000   
75%             7.000000               NaN           59.000000   
max            14.000000               NaN          114.000000   

        num_procedures  num_medications  number_outpatient  number_emergency  \
count      9999.000000      9999.000000        9999.000000       9999.000000   
unique             NaN              NaN                NaN               NaN   
top                NaN              NaN                NaN               NaN   
freq               NaN              NaN                NaN               NaN   
mean          1.445645        15.303830           0.109311          0.064906   
std           1.724649         7.915417           0.589934          0.442184   
min           0.000000         1.000000           0.000000          0.000000   
25%           0.000000        10.000000           0.000000          0.000000   
50%           1.000000        14.000000           0.000000          0.000000   
75%           2.000000        19.000000           0.000000          0.000000   
max           6.000000        62.000000          12.000000         22.000000   

        number_inpatient  number_diagnoses max_glu_serum A1Cresult metformin  \
count        9999.000000       9999.000000          9999      9999      9999   
unique               NaN               NaN             4         4         4   
top                  NaN               NaN          None      None        No   
freq                 NaN               NaN          9048      8177      8415   
mean            0.659166          6.892089           NaN       NaN       NaN   
std             1.351151          2.008747           NaN       NaN  

In [470]:
print('Unique pairs before:')
print(get_unique_pairs(df))

df.drop('encounter_id', axis=1, inplace=True)
#TODO: Could drop subsequent patient visits
df.drop('patient_nbr', axis=1, inplace=True)

print('Unique pairs after:')
print(get_unique_pairs(df))

Unique pairs before:
[('encounter_id', 9999), ('patient_nbr', 7944), ('race', 6), ('gender', 2), ('age', 10), ('admission_type_id', 7), ('discharge_disposition_id', 18), ('admission_source_id', 11), ('time_in_hospital', 14), ('medical_specialty', 50), ('num_lab_procedures', 108), ('num_procedures', 7), ('num_medications', 59), ('number_outpatient', 12), ('number_emergency', 12), ('number_inpatient', 17), ('number_diagnoses', 9), ('max_glu_serum', 4), ('A1Cresult', 4), ('metformin', 4), ('repaglinide', 4), ('nateglinide', 2), ('chlorpropamide', 2), ('glimepiride', 4), ('glipizide', 4), ('glyburide', 4), ('tolbutamide', 2), ('pioglitazone', 4), ('rosiglitazone', 4), ('acarbose', 3), ('miglitol', 2), ('troglitazone', 2), ('tolazamide', 2), ('insulin', 4), ('glyburide-metformin', 2), ('change', 2), ('diabetesMed', 2), ('readmitted', 3)]
Unique pairs after:
[('race', 6), ('gender', 2), ('age', 10), ('admission_type_id', 7), ('discharge_disposition_id', 18), ('admission_source_id', 11), ('ti

In [471]:
df.head()

race  gender      age  admission_type_id  \
0        Caucasian  Female   [0-10)                  6   
1        Caucasian  Female  [10-20)                  1   
2  AfricanAmerican  Female  [20-30)                  1   
3        Caucasian    Male  [30-40)                  1   
4        Caucasian    Male  [40-50)                  1   

   discharge_disposition_id  admission_source_id  time_in_hospital  \
0                        25                    1                 1   
1                         1                    7                 3   
2                         1                    7                 2   
3                         1                    7                 2   
4                         1                    7                 1   

          medical_specialty  num_lab_procedures  num_procedures  \
0  Pediatrics-Endocrinology                  41               0   
1                   unknown                  59               0   
2                   unknown                  11               5   
3                   unknown                  44               1   
4                   unknown                  51               0   

   num_medications  number_outpatient  number_emergency  number_inpatient  \
0                1                  0                 0                 0   
1               18                  0                 0                 0   
2               13                  2                 0                 1   
3               16                  0                 0                 0   
4                8                  0                 0                 0   

   number_diagnoses max_glu_serum A1Cresult metformin repaglinide nateglinide  \
0                 1          None      None        No          No          No   
1                 9          None      None        No          No          No   
2                 6          None      None        No          No          No   
3                 7          None      None        No          No          No   
4                 5          None      None        No          No          No   

  chlorpropamide glimepiride glipizide glyburide tolbutamide pioglitazone  \
0             No          No        No        No          No           No   
1             No          No        No        No          No           No   
2             No          No    Steady        No          No           No   
3             No          No        No        No          No           No   
4             No          No    Steady        No          No           No   

  rosiglitazone acarbose miglitol troglitazone tolazamide insulin  \
0            No       No       No           No         No      No   
1            No       No       No           No         No      Up   
2            No       No       No           No         No      No   
3            No       No       No           No         No      Up   
4            No       No       No           No         No  Steady   

  glyburide-metformin change diabetesMed readmitted  
0                  No     No          No         NO  
1                  No     Ch         Yes        >30  
2                  No     No         Yes         NO  
3                  No     Ch         Yes         NO  
4                  No     Ch         Yes         NO

#### Encode categorical values

* Encode `age` as the medium between the two boundaries
* Encode `[admission_type_id, discharge_disposition_id, admission_source_id]` and all non-numerical columns to binary format

In [472]:
num_ages = np.linspace(5, 95, 10)
cat_ages = df['age'].unique()

for cat, num in zip(cat_ages, num_ages):
    print(cat,'with', num)
    df['age'].replace(to_replace=cat, value=num, inplace=True)

df.describe(include='all')

[0-10) with 5.0
[10-20) with 15.0
[20-30) with 25.0
[30-40) with 35.0
[40-50) with 45.0
[50-60) with 55.0
[60-70) with 65.0
[70-80) with 75.0
[80-90) with 85.0
[90-100) with 95.0


race  gender          age  admission_type_id  \
count        9999    9999  9999.000000        9999.000000   
unique          6       2          NaN                NaN   
top     Caucasian  Female          NaN                NaN   
freq         7181    5390          NaN                NaN   
mean          NaN     NaN    63.574857           2.455546   
std           NaN     NaN    16.653367           1.865877   
min           NaN     NaN     5.000000           1.000000   
25%           NaN     NaN    55.000000           1.000000   
50%           NaN     NaN    65.000000           2.000000   
75%           NaN     NaN    75.000000           3.000000   
max           NaN     NaN    95.000000           8.000000   

        discharge_disposition_id  admission_source_id  time_in_hospital  \
count                9999.000000          9999.000000       9999.000000   
unique                       NaN                  NaN               NaN   
top                          NaN                  NaN               NaN   
freq                         NaN                  NaN               NaN   
mean                    4.733073             6.721972          4.838984   
std                     6.791574             4.995468          3.167283   
min                     1.000000             1.000000          1.000000   
25%                     1.000000             2.000000          2.000000   
50%                     1.000000             7.000000          4.000000   
75%                     6.000000             7.000000          7.000000   
max                    25.000000            20.000000         14.000000   

       medical_specialty  num_lab_procedures  num_procedures  num_medications  \
count               9999         9999.000000     9999.000000      9999.000000   
unique                50                 NaN             NaN              NaN   
top              unknown                 NaN             NaN              NaN   
freq                3637                 NaN             NaN              NaN   
mean                 NaN           46.870087        1.445645        15.303830   
std                  NaN           18.128148        1.724649         7.915417   
min                  NaN            1.000000        0.000000         1.000000   
25%                  NaN           35.000000        0.000000        10.000000   
50%                  NaN           47.000000        1.000000        14.000000   
75%                  NaN           59.000000        2.000000        19.000000   
max                  NaN          114.000000        6.000000        62.000000   

        number_outpatient  number_emergency  number_inpatient  \
count         9999.000000       9999.000000       9999.000000   
unique                NaN               NaN               NaN   
top                   NaN               NaN               NaN   
freq                  NaN               NaN               NaN   
mean             0.109311          0.064906          0.659166   
std              0.589934          0.442184          1.351151   
min              0.000000          0.000000          0.000000   
25%              0.000000          0.000000          0.000000   
50%              0.000000          0.000000          0.000000   
75%              0.000000          0.000000          1.000000   
max             12.000000         22.000000         17.000000   

        number_diagnoses max_glu_serum A1Cresult metformin repaglinide  \
count        9999.000000          9999      9999      9999        9999   
unique               NaN             4         4         4           4   
top                  NaN          None      None        No          No   
freq                 NaN          9048      8177      8415        9906   
mean            6.892089           NaN       NaN       NaN         NaN   
std             2.008747           NaN       NaN       NaN         NaN   
min             1.000000           NaN       NaN       NaN         NaN   
25%             5.000000         

In [473]:
labels = df["readmitted"].values
df.drop("readmitted", axis=1, inplace=True)
df.head()

race  gender   age  admission_type_id  discharge_disposition_id  \
0        Caucasian  Female   5.0                  6                        25   
1        Caucasian  Female  15.0                  1                         1   
2  AfricanAmerican  Female  25.0                  1                         1   
3        Caucasian    Male  35.0                  1                         1   
4        Caucasian    Male  45.0                  1                         1   

   admission_source_id  time_in_hospital         medical_specialty  \
0                    1                 1  Pediatrics-Endocrinology   
1                    7                 3                   unknown   
2                    7                 2                   unknown   
3                    7                 2                   unknown   
4                    7                 1                   unknown   

   num_lab_procedures  num_procedures  num_medications  number_outpatient  \
0                  41               0                1                  0   
1                  59               0               18                  0   
2                  11               5               13                  2   
3                  44               1               16                  0   
4                  51               0                8                  0   

   number_emergency  number_inpatient  number_diagnoses max_glu_serum  \
0                 0                 0                 1          None   
1                 0                 0                 9          None   
2                 0                 1                 6          None   
3                 0                 0                 7          None   
4                 0                 0                 5          None   

  A1Cresult metformin repaglinide nateglinide chlorpropamide glimepiride  \
0      None        No          No          No             No          No   
1      None        No          No          No             No          No   
2      None        No          No          No             No          No   
3      None        No          No          No             No          No   
4      None        No          No          No             No          No   

  glipizide glyburide tolbutamide pioglitazone rosiglitazone acarbose  \
0        No        No          No           No            No       No   
1        No        No          No           No            No       No   
2    Steady        No          No           No            No       No   
3        No        No          No           No            No       No   
4    Steady        No          No           No            No       No   

  miglitol troglitazone tolazamide insulin glyburide-metformin change  \
0       No           No         No      No                  No     No   
1       No           No         No      Up                  No     Ch   
2       No           No         No      No                  No     No   
3       No           No         No      Up                  No     Ch   
4       No           No         No  Steady                  No     Ch   

  diabetesMed  
0          No  
1         Yes  
2         Yes  
3         Yes  
4         Yes

In [474]:
id_cols = ['admission_type_id', 'discharge_disposition_id', 'admission_source_id']
categorical_cols = df.select_dtypes(include='object').columns
categorical_cols

Index(['race', 'gender', 'medical_specialty', 'max_glu_serum', 'A1Cresult',
       'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide',
       'glimepiride', 'glipizide', 'glyburide', 'tolbutamide', 'pioglitazone',
       'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone', 'tolazamide',
       'insulin', 'glyburide-metformin', 'change', 'diabetesMed'],
      dtype='object')

In [475]:
from sklearn.preprocessing import LabelBinarizer

to_bin = np.concatenate([id_cols, categorical_cols])
print(to_bin)
to_bin.shape

['admission_type_id' 'discharge_disposition_id' 'admission_source_id'
 'race' 'gender' 'medical_specialty' 'max_glu_serum' 'A1Cresult'
 'metformin' 'repaglinide' 'nateglinide' 'chlorpropamide' 'glimepiride'
 'glipizide' 'glyburide' 'tolbutamide' 'pioglitazone' 'rosiglitazone'
 'acarbose' 'miglitol' 'troglitazone' 'tolazamide' 'insulin'
 'glyburide-metformin' 'change' 'diabetesMed']


(26,)

In [476]:
df.head()

race  gender   age  admission_type_id  discharge_disposition_id  \
0        Caucasian  Female   5.0                  6                        25   
1        Caucasian  Female  15.0                  1                         1   
2  AfricanAmerican  Female  25.0                  1                         1   
3        Caucasian    Male  35.0                  1                         1   
4        Caucasian    Male  45.0                  1                         1   

   admission_source_id  time_in_hospital         medical_specialty  \
0                    1                 1  Pediatrics-Endocrinology   
1                    7                 3                   unknown   
2                    7                 2                   unknown   
3                    7                 2                   unknown   
4                    7                 1                   unknown   

   num_lab_procedures  num_procedures  num_medications  number_outpatient  \
0                  41               0                1                  0   
1                  59               0               18                  0   
2                  11               5               13                  2   
3                  44               1               16                  0   
4                  51               0                8                  0   

   number_emergency  number_inpatient  number_diagnoses max_glu_serum  \
0                 0                 0                 1          None   
1                 0                 0                 9          None   
2                 0                 1                 6          None   
3                 0                 0                 7          None   
4                 0                 0                 5          None   

  A1Cresult metformin repaglinide nateglinide chlorpropamide glimepiride  \
0      None        No          No          No             No          No   
1      None        No          No          No             No          No   
2      None        No          No          No             No          No   
3      None        No          No          No             No          No   
4      None        No          No          No             No          No   

  glipizide glyburide tolbutamide pioglitazone rosiglitazone acarbose  \
0        No        No          No           No            No       No   
1        No        No          No           No            No       No   
2    Steady        No          No           No            No       No   
3        No        No          No           No            No       No   
4    Steady        No          No           No            No       No   

  miglitol troglitazone tolazamide insulin glyburide-metformin change  \
0       No           No         No      No                  No     No   
1       No           No         No      Up                  No     Ch   
2       No           No         No      No                  No     No   
3       No           No         No      Up                  No     Ch   
4       No           No         No  Steady                  No     Ch   

  diabetesMed  
0          No  
1         Yes  
2         Yes  
3         Yes  
4         Yes

In [477]:
from sklearn.preprocessing import LabelBinarizer

def bin_column(df, cols):
    return pd.get_dummies(df, columns=cols, drop_first=True)

df = bin_column(df, to_bin)
df

age  time_in_hospital  num_lab_procedures  num_procedures  \
0      5.0                 1                  41               0   
1     15.0                 3                  59               0   
2     25.0                 2                  11               5   
3     35.0                 2                  44               1   
4     45.0                 1                  51               0   
...    ...               ...                 ...             ...   
9994  55.0                 3                  49               0   
9995  55.0                 1                  43               2   
9996  75.0                 4                  64               0   
9997  65.0                 1                  72               0   
9998  95.0                 5                  38               0   

      num_medications  number_outpatient  number_emergency  number_inpatient  \
0                   1                  0                 0                 0   
1                  18                  0                 0                 0   
2                  13                  2                 0                 1   
3                  16                  0                 0                 0   
4                   8                  0                 0                 0   
...               ...                ...               ...               ...   
9994               21                  0                 0                 1   
9995                7                  0                 0                 0   
9996                7                  0                 0                 0   
9997               14                  0                 0                 0   
9998               11                  0                 0                 0   

      number_diagnoses  admission_type_id_2  admission_type_id_3  \
0                    1                    0                    0   
1                    9                    0                    0   
2                    6                    0                    0   
3                    7                    0                    0   
4                    5                    0                    0   
...                ...                  ...                  ...   
9994                 6                    1                    0   
9995                 5                    1                    0   
9996                 9                    0                    0   
9997                 8                    0                    0   
9998                 5                    1                    0   

      admission_type_id_4  admission_type_id_5  admission_type_id_6  \
0                       0                    0                    1   
1                       0                    0                    0   
2                       0                    0                    0   
3                       0                    0                    0   
4                       0                    0                    0   
...                   ...                  ...                  ...   
9994                    0                    0                    0   
9995                    0                    0                    0   
9996                    0                    0                    0   
9997                    0                    0                    1   
9998                    0                    0                    0   

      admission_type_id_8  discharge_disposition_id_2  \
0                       0                           0   
1                       0                           0   
2                       0                           0   
3                       0                           0   
4                       0                           0   
...                   ...                         ...   
9994                    0                           0   
9995                    0                           0   
9996                    0                     

## Split into train/test & Scale
* `from sklearn.model_selection import StratifiedShuffleSplit`
* `from sklearn.preprocessing import StandardScaler`

In [478]:
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.preprocessing import StandardScaler

# Split into train and test
X_all, y_all = df.values, labels

X_all = StandardScaler().fit_transform(X_all)

sss = StratifiedShuffleSplit(n_splits=1, random_state=42)
train_full_idx, test_idx = next(sss.split(X_all, y_all))


X_train_full, y_train_full = X_all[train_full_idx], y_all[train_full_idx]
X_test, y_test = X_all[test_idx], y_all[test_idx]

# Further split train into train and validation
sss = StratifiedShuffleSplit(n_splits=1, random_state=42, test_size=0.2)

train_idx, dev_idx = next(sss.split(X_train_full, y_train_full))
X_train, y_train = X_train_full[train_idx], y_train_full[train_idx]
X_dev, y_dev = X_train_full[dev_idx], y_train_full[dev_idx]

print(f"Shape of train: {X_train.shape}")
print(f"Shape of dev: {X_dev.shape}")
print(f"Shape of test: {X_test.shape}")

Shape of train: (7199, 138)
Shape of dev: (1800, 138)
Shape of test: (1000, 138)


## Model fitting

In [479]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, precision_score, recall_score

def eval_model(model, X_train, y_train, X_test, y_test):
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    
    print(f"Model {model}")
    print(f"Accuracy score: {accuracy_score(y_test, pred)}")
    print(f"Precision score: {precision_score(y_test, pred, average='weighted')}")
    print(f"Recall score: {recall_score(y_test, pred, average='weighted')}")
    print(f"F1 score: {f1_score(y_test, pred, average='weighted')}")
    print(f"Confusion matrix:\n{confusion_matrix(y_test, pred)}")
    print("---------------------------------------------------------------\n\n")

In [480]:
from sklearn.base import BaseEstimator # No **args, **kwargs
from sklearn.base import TransformerMixin # .fit_transform() 'functionality'

class StupidPredictor(BaseEstimator, TransformerMixin):
    def __init__(self):
        self.will_say = None
    def fit(self, X, y):
        self.will_say = y[0]
    def predict(self, X):
        return np.full_like(X[:, 0], self.will_say, dtype='object')

In [484]:
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier

eval_model(StupidPredictor(), X_train, y_train, X_dev, y_dev)
eval_model(LogisticRegression(), X_train, y_train, X_dev, y_dev)
eval_model(SGDClassifier(), X_train, y_train, X_dev, y_dev)
eval_model(GaussianNB(), X_train, y_train, X_dev, y_dev)
eval_model(DecisionTreeClassifier(), X_train, y_train, X_dev, y_dev)
eval_model(RandomForestClassifier(), X_train, y_train, X_dev, y_dev)
eval_model(ExtraTreesClassifier(), X_train, y_train, X_dev, y_dev)

Model StupidPredictor()
Accuracy score: 0.3333333333333333
Precision score: 0.1111111111111111
Recall score: 0.3333333333333333
F1 score: 0.16666666666666666
Confusion matrix:
[[  0 600   0]
 [  0 600   0]
 [  0 600   0]]
---------------------------------------------------------------




/home/simeon/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/simeon/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/simeon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/simeon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


Model LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)
Accuracy score: 0.5144444444444445
Precision score: 0.5192294279004749
Recall score: 0.5144444444444445
F1 score: 0.5148495610661182
Confusion matrix:
[[326 148 126]
 [128 251 221]
 [ 67 184 349]]
---------------------------------------------------------------


Model SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=None, penalty='l2',
              power_t=0.5, random_state=None, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbo

/home/simeon/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/simeon/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


Model ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
                     max_depth=None, max_features='auto', max_leaf_nodes=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=1, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
                     oob_score=False, random_state=None, verbose=0,
                     warm_start=False)
Accuracy score: 0.4738888888888889
Precision score: 0.47666153665465916
Recall score: 0.4738888888888889
F1 score: 0.47449834007780844
Confusion matrix:
[[326 165 109]
 [183 259 158]
 [104 228 268]]
---------------------------------------------------------------




## Evaluation
* RMSE & accuracy
* Confusion matrix
* F1 (or Fx) scores & compare

In [485]:
eval_model(LogisticRegression(), X_train_full, y_train_full, X_test, y_test)

/home/simeon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/simeon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


Model LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)
Accuracy score: 0.535
Precision score: 0.5354632428177883
Recall score: 0.535
F1 score: 0.5347512840685209
Confusion matrix:
[[207  68  58]
 [ 70 143 120]
 [ 45 104 185]]
---------------------------------------------------------------


